packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  systemjs-webpack-interop@*:
    dependencies:
      webpack: "*"
  tsdx@*:
    dependencies:
      babel-jest: "*"
      ts-jest: "*"
  webpack-config-single-spa@*:
    dependencies:
      "@babel/core": "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
