yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  "systemjs-webpack-interop@*":
    dependencies:
      "webpack": "*"
  "webpack-config-single-spa@*":
    dependencies:
      "@babel/core": "*"
      "webpack": "*"
