name: kinetics-auth

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/kinetics-auth.yaml
      - packages/kinetics-auth/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/kinetics-auth.yaml
      - packages/kinetics-auth/**

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/kinetics-auth
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn workspaces foreach -ptR --from '@kinetics-dev/auth' run prepack
      - name: yarn test
        run: |
          echo VITE_TEST_CLIENT_ID=${{ secrets.VITE_TEST_CLIENT_ID }} >> .env
          export CYPRESS_TEST_USERNAME=${{ secrets.CYPRESS_TEST_USERNAME }}
          export CYPRESS_TEST_PASSWORD=${{ secrets.CYPRESS_TEST_PASSWORD }}
          yarn test
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn npm publish --tolerate-republish
