name: kinetics-auth

on:
  push:
    branches: [main]
    paths:
      - packages/kinetics-auth/**
      - .github/workflows/kinetics-auth.yaml
  pull_request:
    branches: [main]
    paths:
      - packages/kinetics-auth/**
      - .github/workflows/kinetics-auth.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/kinetics-auth
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
      - run: yarn build
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn npm publish --tolerate-republish
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
