name: webpack-config

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/webpack-config.yaml
      - packages/webpack-config/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/webpack-config.yaml
      - packages/webpack-config/**

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/webpack-config
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
      - run: yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn npm publish --tolerate-republish
